const stages=[
 {slug:'before-start',name:'시작 판단',icon:'①',summary:'생활 기반과 창업 목표를 분리해 작은 실험을 설계합니다.',tasks:['월 생활비와 창업 가능 자금을 분리하기','내 경력·강점에서 해결할 문제 3개 찾기','퇴사 전 4주 검증 계획 만들기'],docs:['startup-diagnosis','living-business-budget','career-strength'],next:'돈을 내고 해결하고 싶은 고객 문제를 한 문장으로 설명할 수 있을 때'},
 {slug:'validation',name:'아이템 검증',icon:'②',summary:'등록보다 먼저 고객의 문제와 지불 의사를 확인합니다.',tasks:['잠재 고객 5명 인터뷰하기','한 장 사업기획서 작성하기','작은 유료 제안으로 반응 확인하기'],docs:['customer-interview','one-page-plan','price-break-even'],next:'누가 왜 구매하는지와 첫 가격 가설을 근거와 함께 설명할 수 있을 때'},
 {slug:'registration',name:'등록 준비',icon:'③',summary:'업종·인허가·사업장·세무 일정을 확인해 등록 순서를 정합니다.',tasks:['업종별 인허가 여부 확인하기','사업장 계약 전 조건 확인하기','개인·법인 선택 근거 기록하기'],docs:['lease-check','registration-checklist','support-docs'],next:'필요한 신고와 서류, 시작일, 비용 처리 기준이 정리되었을 때'},
 {slug:'first-sales',name:'첫 거래',icon:'④',summary:'견적부터 계약, 납품, 입금까지 거래의 기본 틀을 만듭니다.',tasks:['업무 범위와 제외 범위 적기','견적·계약 조건 확인하기','납품·검수와 입금 절차 정하기'],docs:['estimate','scope-schedule','contract-review'],next:'첫 거래가 입금까지 마무리되고 같은 방식으로 한 번 더 진행할 수 있을 때'},
 {slug:'operations',name:'운영 안정',icon:'⑤',summary:'현금흐름과 고객·반복 업무를 보이게 관리합니다.',tasks:['월간 매출·비용 기록하기','상담과 고객 진행 상태 정리하기','반복 업무 체크리스트 만들기'],docs:['cashflow-6m','customer-crm','monthly-sales-cost'],next:'3개월 이상 흐름을 확인하고 병목과 개선 우선순위를 설명할 수 있을 때'},
 {slug:'growth',name:'성장·전환',icon:'⑥',summary:'잘 되는 고객·채널에 집중하고 외주와 자동화를 설계합니다.',tasks:['수익성 높은 고객 유형 찾기','외주 발주 기준 정하기','자동화할 반복 업무 선택하기'],docs:['outsourcing','recurring-checklist','monthly-sales-cost'],next:'확장 비용과 예상 효과, 중단 기준을 숫자와 일정으로 정했을 때'},
 {slug:'restart',name:'재도전',icon:'⑦',summary:'정리할 것과 다시 살릴 자산을 구분해 다음 실험을 준비합니다.',tasks:['고정비와 미수금 점검하기','고객·콘텐츠·경험 자산 정리하기','작은 재검증 범위 정하기'],docs:['monthly-sales-cost','receivables','startup-diagnosis'],next:'보호할 자원과 새 검증 가설, 중단 기준을 명확히 했을 때'}
];
const resources=[
 ['startup-diagnosis','창업 준비 진단표','DOCX','문서형','시작 판단','상황과 준비 수준을 스스로 점검합니다.'],['living-business-budget','생활비·사업비 분리 계산표','XLSX','계산·관리표','시작 판단','생활자금 보호선과 창업 가능 예산을 계산합니다.'],['career-strength','경력·강점 사업화 워크시트','DOCX','문서형','시작 판단','경험을 고객 문제와 연결합니다.'],['customer-interview','고객 인터뷰 기록지','DOCX','문서형','아이템 검증','고객의 실제 행동과 표현을 기록합니다.'],['one-page-plan','한 장 사업기획서','DOCX','문서형','아이템 검증','고객·문제·해결·수익 구조를 한 장에 정리합니다.'],['price-break-even','가격·손익분기 계산표','XLSX','계산·관리표','아이템 검증','가격과 판매량에 따른 손익분기를 계산합니다.'],['cashflow-6m','6개월 현금흐름표','XLSX','계산·관리표','운영 안정','월별 입출금과 월말 잔액을 관리합니다.'],['lease-check','사업장 계약 전 확인표','DOCX','문서형','등록 준비','용도·인허가·비용 조건을 계약 전에 확인합니다.'],['registration-checklist','등록·인허가 준비 체크리스트','DOCX','문서형','등록 준비','업종별 확인 항목과 기관 문의 결과를 기록합니다.'],['support-docs','지원사업 제출자료 관리표','XLSX','계산·관리표','등록 준비','공고별 제출자료와 준비 상태를 관리합니다.'],['estimate','견적서','XLSX','계산·관리표','첫 거래','공급가액과 세액, 합계를 자동 계산합니다.'],['scope-schedule','업무범위·일정표','DOCX','문서형','첫 거래','산출물·일정·역할과 제외 범위를 합의합니다.'],['contract-review','서비스 계약 검토용 양식','DOCX','문서형','첫 거래','계약 핵심 조건을 빠짐없이 검토합니다.'],['change-request','추가 작업 요청·승인서','DOCX','문서형','첫 거래','추가 범위·비용·일정 변경을 기록합니다.'],['delivery-check','납품·검수 확인서','DOCX','문서형','첫 거래','납품물과 수정·검수 상태를 확인합니다.'],['receivables','입금·미수금 관리표','XLSX','계산·관리표','운영 안정','청구·입금·미수 상태를 관리합니다.'],['customer-crm','고객·상담 관리표','XLSX','계산·관리표','운영 안정','상담 단계와 다음 연락일을 기록합니다.'],['monthly-sales-cost','월간 매출·비용 관리표','XLSX','계산·관리표','운영 안정','월 손익과 주요 비용을 확인합니다.'],['recurring-checklist','반복 업무 체크리스트','XLSX','계산·관리표','성장·전환','주기별 반복 업무의 완료 상태를 관리합니다.'],['outsourcing','외주 발주·진행 관리표','XLSX','계산·관리표','성장·전환','외주 범위·마감·비용·진행 상태를 관리합니다.']
].map(([slug,title,format,type,stage,desc])=>({slug,title,format,type,stage,desc}));
const supports=[
 {slug:'k-startup',name:'K-Startup 창업지원포털',org:'창업진흥원',type:'교육',age:'정보 확인',region:'전국',stage:'예비·창업·성장',url:'https://www.k-startup.go.kr/web',checked:'2026-09-29',desc:'창업 단계·연령·관심 분야로 공고와 교육, 창업 정보를 탐색하는 공식 경로입니다.'},
 {slug:'bizinfo',name:'기업마당 지원사업 공고',org:'중소벤처기업부',type:'판로·마케팅',age:'공고별 상이',region:'전국·지역',stage:'운영·성장',url:'https://www.bizinfo.go.kr/web/index.do',checked:'2026-09-29',desc:'부처·지자체의 중소기업 지원사업을 분야별로 확인하는 공식 경로입니다.'},
 {slug:'k-startup-edu',name:'창업에듀 온라인 교육',org:'창업진흥원',type:'교육',age:'연령 제한 없음',region:'온라인',stage:'전 단계',url:'https://www.k-startup.go.kr/edu/home/main/index',checked:'2026-09-29',desc:'예비창업자와 창업자를 위한 단계별 이론·실무 강좌를 확인하는 경로입니다.'},
 {slug:'kosmes',name:'중소벤처기업진흥공단 정책 안내',org:'중소벤처기업진흥공단',type:'융자',age:'사업별 상이',region:'전국',stage:'등록 후·성장',url:'https://www.kosmes.or.kr/',checked:'2026-09-29',desc:'정책자금·수출·인력 등 기업 지원 경로를 확인합니다. 금액과 자격은 세부 공고를 확인하세요.'},
 {slug:'wbiz',name:'여성기업 종합정보포털',org:'한국여성경제인협회',type:'판로·마케팅',age:'정보 확인',region:'전국',stage:'전 단계',url:'https://www.wbiz.or.kr/',checked:'2026-09-29',desc:'여성기업 확인, 교육, 판로 등 지원 정보를 확인하는 공식 경로입니다.'},
 {slug:'saeil',name:'여성새로일하기센터',org:'성평등가족부·고용노동부',type:'교육',age:'정보 확인',region:'지역 센터',stage:'경력 공백 후 시작',url:'https://saeil.mogef.go.kr/',checked:'2026-09-29',desc:'경력 공백 여성의 직업교육과 취·창업 지원을 지역 센터에서 확인하는 경로입니다.'},
 {slug:'credit-guarantee',name:'지역 신용보증재단 찾기',org:'신용보증재단중앙회',type:'보증',age:'연령 제한 없음',region:'사업장 지역',stage:'등록 준비·운영',url:'https://www.koreg.or.kr/',checked:'2026-09-29',desc:'사업장 소재지의 지역 신용보증재단과 보증 상품 확인 경로입니다.'},
 {slug:'startup-space',name:'창업공간·보육기관 탐색',org:'K-Startup',type:'공간',age:'공고별 상이',region:'사업장 지역',stage:'예비·초기',url:'https://www.k-startup.go.kr/web',checked:'2026-09-29',desc:'창업인프라지도에서 지역별 창업공간과 주관기관을 탐색합니다.'}
];
const stories=[
 {slug:'junho',title:'퇴사 전 고객부터 만난 이준호',tag:'가상 사례 · 33세',icon:'🧑🏻‍💻',lead:'회사 마케팅 실무 7년을 바탕으로 소상공인 콘텐츠 운영 서비스를 준비합니다.',steps:[['고민','퇴사 시점, 고객 확보, 가격과 견적·계약이 막막했습니다.'],['선택','등록보다 고객 검증을 먼저 하고, 퇴사 판단과 사업 검증을 분리했습니다.'],['실행','잠재 고객 인터뷰 → 작은 유료 제안 → 첫 견적·계약 → 입금 순서로 진행했습니다.'],['사용한 자료','고객 인터뷰 기록지, 가격·손익분기 계산표, 견적서, 계약 검토용 양식'],['다음 행동','반복 고객의 공통 문제를 모아 서비스 범위와 월 운영 프로세스를 다듬습니다.']]},
 {slug:'jihyun',title:'20년 경력을 작은 프로그램으로 만든 김지현',tag:'가상 사례 · 54세',icon:'👩🏻‍🏫',lead:'기업 교육·운영 경험을 기업과 지역기관 대상 교육 프로그램으로 전환합니다.',steps:[['고민','생활자금을 지키면서 경력을 상품화하고 디지털 고객을 만나는 방법이 필요했습니다.'],['선택','퇴직금이나 직장 인맥을 가정하지 않고, 가용시간과 돌봄 일정을 먼저 확인했습니다.'],['실행','경력 재정리 → 자금 구분 → 작은 프로그램 실습 → 단체 고객 제안 순서로 움직였습니다.'],['사용한 자료','생활비·사업비 분리 계산표, 경력·강점 사업화 워크시트, 한 장 사업기획서'],['다음 행동','경력 공백 후 다시 시작한다면 짧은 디지털 실습을 주간 일정에 넣고 작은 결과물을 축적합니다.']]},
 {slug:'founder',title:'시행착오를 순서도로 바꾸다',tag:'서비스 기획 배경',icon:'🧭',lead:'임헌수 대표가 거상스쿨·거상마케팅센터를 운영하고 새로운 법인을 설립하며 겪은 시행착오에서 출발했습니다.',steps:[['문제','창업 정보가 기관과 시점별로 흩어져 있어 지금 무엇을 해야 하는지 판단하기 어려웠습니다.'],['기획 원칙','정보를 많이 보여주기보다 단계별 다음 행동, 필요한 자료, 공식 확인 경로를 연결합니다.'],['서비스 연결','무료 진단과 실무 자료로 실행을 돕고, 더 깊은 교육·컨설팅·제작·마케팅 도움이 필요할 때 선택할 수 있게 합니다.'],['제한','구체적인 사건·대화·매출·성과는 확인되지 않아 소개하지 않습니다.'],['다음 행동','진단으로 현재 단계를 확인하고 오늘 할 일 하나를 완료해 보세요.']]}
];
const services=[['직접 배우기','거상스쿨 교육','창업 실습과 AI 마케팅을 직접 익히고 싶은 분','강의와 실습 중심으로 진행하며 일정과 비용은 상담 후 확인합니다.','📘'],['사업·마케팅 컨설팅','우선순위와 실행계획 정리','아이템·고객·가격·마케팅 판단이 필요한 분','현재 자료를 함께 살펴보고 다음 실험과 점검 기준을 정합니다.','🧭'],['홈페이지 기획·제작','신뢰받는 온라인 사업 기반','사업 설명과 문의 흐름을 웹으로 만들고 싶은 분','콘텐츠 구조, 화면, 개발과 공개 준비를 단계별로 진행합니다.','🖥️'],['마케팅·자동화 운영','반복 업무와 고객 여정 정리','콘텐츠·상담·고객 관리 흐름을 개선하려는 분','현재 프로세스를 진단하고 필요한 채널과 자동화 범위를 설계합니다.','⚙️']];
const store={get(){try{return JSON.parse(localStorage.getItem('gs-navi')||'{}')}catch{return{}}},set(data){localStorage.setItem('gs-navi',JSON.stringify(data));updateNoteCount()},patch(part){this.set({...this.get(),...part})},clear(){localStorage.removeItem('gs-navi');updateNoteCount()}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('#main');
function updateNoteCount(){const s=store.get();const n=(s.savedResources||[]).length+(s.savedSupports||[]).length+(s.completed||[]).length;document.querySelector('#note-count').textContent=n}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function pageHero(eyebrow,title,desc){return `<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">홈</a> / ${esc(title)}</div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="section-desc">${desc}</p></div></section>`}
function stageStrip(active){return `<div class="roadmap-strip">${stages.map((s,i)=>`<a class="roadmap-step ${active===s.slug?'active':''}" href="/roadmap/${s.slug}/"><span>${i+1}</span>${s.name}</a>`).join('')}</div>`}
function home(){const s=store.get(),stage=stages.find(x=>x.slug===s.stage)||stages[1];const tasks=s.resultTasks||['생활비와 사업비 나누기','고객 인터뷰 질문 만들기','등록 전 지원조건 확인'];return `<section class="hero"><div class="container hero-grid"><div><div class="eyebrow">퇴사 전 준비부터 첫 매출까지</div><h1>막막한 창업,<br><span>지금 할 일부터.</span></h1><p class="hero-copy">내 단계에 맞는 준비, 서류, 지원사업을 한곳에서.<br>처음 시작하는 사장님의 다음 한 걸음을 안내합니다.</p><div class="actions"><a class="btn btn-primary" href="/start/">내 창업 단계 찾기</a><a class="btn" href="/resources/">무료 양식 둘러보기</a></div><p class="tagline-note">청년부터 중장년까지, 나의 상황에 맞게</p></div><div class="hero-note"><div class="desk-art"></div><div class="note-card"><div class="note-top"><h2>나의 창업노트</h2><span class="pill">${s.stage?stage.name:'진단 전 · 예시'}</span></div><h3>오늘 할 일 3가지</h3><div class="task-list">${tasks.map((t,i)=>`<div class="task ${i===0?'done':''}"><span class="check">${i===0?'✓':''}</span>${esc(t)}</div>`).join('')}</div><a class="note-footer" href="${s.stage?'/my/':'/start/'}">${s.stage?'내 창업노트 보기':'진단하고 실제 결과 받기'}</a></div></div></div></section>
<section class="section-sm section-soft"><div class="container"><h2 class="section-title">지금, 어떤 상황이신가요?</h2><div class="situation-grid">${[['employee','💼','재직 중 준비'],['retired','🌅','퇴직 후 시작'],['career','📖','경력 공백 후 시작'],['business','🏪','이미 사업 중']].map(x=>`<a class="situation-card" href="/start/?situation=${x[0]}"><span class="icon">${x[1]}</span>${x[2]} <span style="margin-left:auto">›</span></a>`).join('')}</div></div></section>
<section class="section"><div class="container"><div class="eyebrow">한눈에 보는 창업 로드맵</div><h2 class="section-title">오늘의 위치와 다음 기준을 확인하세요</h2>${stageStrip(s.stage||'validation')}</div></section>
<section class="section section-soft"><div class="container split"><div><div class="eyebrow">바로 쓰는 실무 양식</div><h2 class="section-title">작성부터 관리까지, 빈칸에서 시작하지 마세요</h2><div class="resource-row">${[resources[1],resources[10],resources[8]].map(r=>`<a class="resource-mini" href="/resources/${r.slug}/"><span class="file-icon">${r.format}</span><strong>${r.title}</strong><div class="meta">빈 양식 · 작성 예시 포함</div></a>`).join('')}</div><p><a class="btn" href="/resources/">전체 자료 보기</a></p></div><div class="card"><div class="eyebrow">내 조건에 맞는 지원사업</div><h2>공고보다 먼저, 확인 경로부터</h2><p class="section-desc">연령·지역·사업 단계의 기준일이 공고마다 다릅니다. 조건을 선택하고 공식 원문에서 최종 확인하세요.</p><div class="filters">${['연령 제한 없음','40대 이상','여성 창업','우리 지역','공간·교육','판로·마케팅'].map(x=>`<a class="chip" href="/support/?q=${encodeURIComponent(x)}">${x}</a>`).join('')}</div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">실전 이야기</div><h2 class="section-title">다른 출발점, 같은 원칙: 작게 확인하고 기록하기</h2><div class="story-grid">${stories.map(x=>`<a class="story-card" href="/stories/${x.slug}/"><div class="story-visual">${x.icon}</div><div class="body"><span class="badge">${x.tag}</span><h3>${x.title}</h3><p>${x.lead}</p></div></a>`).join('')}</div></div></section>
<section class="section section-navy"><div class="container"><div class="eyebrow" style="color:#86aaff">교육·도움받기</div><h2 class="section-title">혼자 막히는 지점은 필요한 방식으로 풀어보세요</h2><div class="service-grid">${services.map(x=>`<div class="service-card"><span class="icon">${x[4]}</span><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div><div class="actions" style="margin-top:28px"><a class="btn btn-ghost-light" href="/help/">도움 방식 살펴보기</a></div></div></section>
<section class="section"><div class="container"><div class="cta-band"><div><div class="eyebrow">오늘 할 일부터 시작해 보세요</div><h2 class="section-title">10개의 질문으로 지금의 단계를 찾습니다</h2></div><a class="btn btn-primary" href="/start/">무료 진단 시작</a></div></div></section>`}
const questions=[
 ['situation','현재 어떤 상황인가요?',[['employee','재직 중 준비'],['retired','퇴직 후 시작'],['career','경력 공백 후 시작'],['business','이미 사업 중'],['unknown','아직 미정']]],
 ['registered','사업자등록을 했나요?',[['no','아직 안 함'],['yes','등록함'],['unknown','아직 미정']]],
 ['item','사업 아이템을 정했나요?',[['no','아직 못 정함'],['yes','정함'],['unknown','더 검토 중']]],
 ['validated','고객 반응을 확인했나요?',[['no','아직 확인 전'],['talked','인터뷰·반응 확인'],['paid','유료 반응 확인'],['unknown','아직 미정']]],
 ['sales','유료 거래가 있었나요?',[['none','아직 없음'],['first','첫 거래 진행 중·완료'],['repeat','반복 매출 발생'],['unknown','아직 미정']]],
 ['concern','현재 가장 큰 고민은 무엇인가요?',[['prepare','준비 순서'],['operate','운영 안정'],['grow','확장·전환'],['restart','축소·정리·재정비'],['unknown','아직 미정']]],
 ['age','연령대를 알려주세요',[['20s','20대 이하'],['30s','30대'],['40s','40대'],['50s','50대'],['60s','60대 이상'],['unknown','답하지 않음']]],
 ['region','거주·사업 예정 지역이 정해졌나요?',[['same','거주지와 사업지가 같음'],['different','서로 다름'],['online','온라인·전국 대상'],['unknown','아직 미정']]],
 ['industry','예정 업종은 무엇인가요?',[['service','서비스·교육'],['retail','도소매·온라인 판매'],['food','식품·외식'],['manufacture','제조'],['unknown','아직 미정']]],
 ['help','지금 필요한 도움은 무엇인가요?',[['documents','서류·양식'],['support','지원 경로'],['education','교육'],['consulting','컨설팅'],['digital','홈페이지·마케팅·자동화']]]
];
let wizard={step:0,answers:{}};
function chooseStage(a){if(a.concern==='restart')return'restart';if(a.concern==='grow'||a.sales==='repeat')return'growth';if(a.registered==='yes'&&a.sales==='none')return'first-sales';if(a.registered==='yes'||a.sales==='first'||a.concern==='operate')return'operations';if(a.validated==='paid'||a.validated==='talked')return'registration';if(a.item==='yes')return'validation';return'before-start'}
function startPage(){const q=new URLSearchParams(location.search).get('situation');wizard={step:0,answers:q?{situation:q}:{}};main.innerHTML=pageHero('창업 단계 진단','지금 필요한 한 걸음을 찾습니다','정답을 맞히는 검사가 아닙니다. 현재 상태를 기록하면 추천 단계와 다음 행동이 달라집니다.')+`<section class="section"><div class="container diagnosis"><div id="wizard"></div></div></section>`;renderQuestion()}
function renderQuestion(){const host=document.querySelector('#wizard');if(!host)return;if(wizard.step>=questions.length){renderResult(host);return}const[key,title,opts]=questions[wizard.step];host.innerHTML=`<div class="progress" aria-label="진행률"><span style="width:${((wizard.step+1)/questions.length)*100}%"></span></div><p class="meta">${wizard.step+1} / ${questions.length}</p><div class="question-card"><h2>${title}</h2><div class="option-grid">${opts.map(([v,l])=>`<button class="option ${wizard.answers[key]===v?'selected':''}" data-value="${v}" type="button">${l}</button>`).join('')}</div><div class="wizard-actions"><button class="btn" id="prev" ${wizard.step===0?'disabled':''}>이전</button><div><button class="btn" id="reset-wizard">다시 시작</button> <button class="btn btn-blue" id="next" ${wizard.answers[key]?'':'disabled'}>다음</button></div></div></div>`;host.querySelectorAll('.option').forEach(b=>b.onclick=()=>{wizard.answers[key]=b.dataset.value;renderQuestion()});host.querySelector('#prev').onclick=()=>{wizard.step--;renderQuestion()};host.querySelector('#reset-wizard').onclick=()=>{wizard={step:0,answers:{}};renderQuestion()};host.querySelector('#next').onclick=()=>{wizard.step++;renderQuestion()}}
function renderResult(host){const slug=chooseStage(wizard.answers),s=stages.find(x=>x.slug===slug);const reason=slug==='before-start'?'아이템과 고객 문제가 아직 정해지지 않아 시작 판단부터 추천합니다.':slug==='validation'?'아이템은 있지만 고객 반응 근거가 더 필요해 검증 단계를 추천합니다.':slug==='registration'?'고객 반응을 확인했고 등록 전 조건과 서류를 정리할 시점입니다.':slug==='first-sales'?'등록 후 첫 유료 거래의 범위·조건·입금 흐름을 만들 시점입니다.':slug==='operations'?'거래 경험을 반복 가능한 운영 구조로 정리할 시점입니다.':slug==='growth'?'반복 매출 또는 확장 고민이 있어 성장·전환 단계가 적합합니다.':'축소·정리 고민을 보호할 자원과 다음 실험으로 나눌 시점입니다.';store.patch({answers:wizard.answers,stage:slug,resultTasks:s.tasks,diagnosedAt:new Date().toISOString()});host.innerHTML=`<div class="question-card"><span class="result-stage">추천 단계 · ${s.name}</span><h2 style="font-size:36px">${s.summary}</h2><p class="notice notice-blue">${reason} 여러 상황이 겹칠 수 있으며, 아래 로드맵에서 단계를 직접 바꿔 볼 수 있습니다.</p><div class="detail-section"><h3>지금 해야 할 일 3개</h3>${s.tasks.map((x,i)=>`<label class="check-row"><input type="checkbox" data-task="${esc(x)}"> <span><strong>${i+1}. ${x}</strong></span></label>`).join('')}</div><div class="detail-section"><h3>관련 자료 3개</h3><div class="list">${s.docs.map(d=>{const r=resources.find(x=>x.slug===d);return `<a class="list-item" href="/resources/${r.slug}/"><div><span class="badge">${r.format}</span><h3>${r.title}</h3><p>${r.desc}</p></div><span>›</span></a>`}).join('')}</div></div><div class="detail-section"><h3>살펴볼 지원 경로</h3><p>공고별 자격과 기준일은 다릅니다. 현재 단계와 지역 조건을 적용한 뒤 공식 원문에서 최종 확인하세요.</p><a class="btn" href="/support/?stage=${slug}">지원 경로 보기</a></div><div class="notice"><strong>다음 단계로 넘어갈 기준</strong><br>${s.next}</div><div class="actions" style="margin-top:24px"><a class="btn btn-blue" href="/my/">내 창업노트 보기</a><a class="btn" href="/help/">관련 교육·도움 보기</a><button class="btn" id="change-stage">단계 직접 변경</button></div></div>`;host.querySelectorAll('[data-task]').forEach(cb=>cb.onchange=()=>{const st=store.get(),set=new Set(st.completed||[]);cb.checked?set.add(cb.dataset.task):set.delete(cb.dataset.task);store.patch({completed:[...set]})});host.querySelector('#change-stage').onclick=()=>location.href='/roadmap/'}
function roadmap(){return pageHero('7단계 창업 로드맵','시작 판단부터 재도전까지','법인 설립을 필수 단계로 가정하지 않습니다. 개인·법인·업종별로 필요한 확인 항목을 구분하세요.')+`<section class="section"><div class="container">${stageStrip(store.get().stage)}<div class="card-grid" style="margin-top:24px">${stages.map((s,i)=>`<a class="card" href="/roadmap/${s.slug}/"><span class="result-stage">${i+1}단계</span><h2>${s.name}</h2><p>${s.summary}</p><strong>먼저 할 일</strong><p>${s.tasks[0]}</p></a>`).join('')}</div></div></section>`}
function roadmapDetail(slug){const s=stages.find(x=>x.slug===slug)||stages[0];return pageHero('창업 로드맵',s.name,s.summary)+`<section class="section"><div class="container content-grid"><nav class="side-nav">${stages.map(x=>`<a href="/roadmap/${x.slug}/">${x.name}</a>`).join('')}</nav><div><div class="detail-section"><h2>이 단계의 고민</h2><p>${s.summary} 개인사업자와 법인은 책임·세무·비용 구조가 다르며, 업종별 인허가는 등록 전에 관할 기관에 확인해야 합니다.</p></div><div class="detail-section"><h2>먼저 할 일</h2><ol class="detail-list">${s.tasks.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="detail-section"><h2>필요한 서류와 실무 양식</h2>${s.docs.map(d=>{const r=resources.find(x=>x.slug===d);return `<a class="list-item" href="/resources/${r.slug}/"><div><span class="badge">${r.format}</span><h3>${r.title}</h3><p>${r.desc}</p></div><span>›</span></a>`}).join('')}</div><div class="detail-section"><h2>지원 탐색</h2><p>거주 지역과 사업장 지역을 구분하고, 사업자등록 전 신청해야 하는지 먼저 확인하세요.</p><a class="btn" href="/support/?stage=${s.slug}">이 단계 지원 경로 보기</a></div><div class="detail-section"><h2>흔한 실수</h2><ul class="detail-list"><li>정보를 많이 모으느라 고객 확인과 실행을 미루는 것</li><li>공고 제목만 보고 자격을 확정하거나 마감일을 추정하는 것</li><li>개인·법인·업종 차이를 확인하지 않고 서류를 그대로 사용하는 것</li></ul></div><div class="notice"><strong>다음 단계 기준</strong><br>${s.next}</div></div></div></section>`}
let resourceFilter={q:'',type:'전체',stage:'전체'};
function resourcesPage(){main.innerHTML=pageHero('서류·양식 자료실','바로 편집하고 쓰는 실무 자료','기관 발급 서류와 공식 제출 서식은 공식 원문을 안내하고, 직접 쓰는 양식은 빈 양식과 가상 예시를 제공합니다.')+`<section class="section"><div class="container"><div class="notice"><strong>자료 구분</strong><br>이 자료실의 20종은 직접 사용하는 실무 양식입니다. 기관 발급 문서나 법정 서식을 대신하지 않습니다.</div><div class="filter-bar" style="margin-top:24px"><input class="input" id="resource-q" type="search" placeholder="자료 이름·설명 검색"><select id="resource-type"><option>전체</option><option>계산·관리표</option><option>문서형</option></select><select id="resource-stage"><option>전체</option>${stages.map(x=>`<option>${x.name}</option>`).join('')}</select><button class="btn" id="resource-reset">초기화</button></div><div id="resource-list" class="list"></div></div></section>`;const draw=()=>{const f=resources.filter(r=>(resourceFilter.type==='전체'||r.type===resourceFilter.type)&&(resourceFilter.stage==='전체'||r.stage===resourceFilter.stage)&&(`${r.title} ${r.desc}`.toLowerCase().includes(resourceFilter.q.toLowerCase())));document.querySelector('#resource-list').innerHTML=f.length?f.map(r=>`<a class="list-item" href="/resources/${r.slug}/"><div><div class="badges"><span class="badge">${r.format}</span><span class="badge">${r.type}</span><span class="badge">${r.stage}</span></div><h3>${r.title}</h3><p>${r.desc}</p></div><span>상세·다운로드 ›</span></a>`).join(''):`<div class="empty"><h3>조건에 맞는 자료가 없습니다</h3><p>검색어를 줄이거나 분류를 초기화해 보세요.</p></div>`};document.querySelector('#resource-q').oninput=e=>{resourceFilter.q=e.target.value;draw()};document.querySelector('#resource-type').onchange=e=>{resourceFilter.type=e.target.value;draw()};document.querySelector('#resource-stage').onchange=e=>{resourceFilter.stage=e.target.value;draw()};document.querySelector('#resource-reset').onclick=()=>{resourceFilter={q:'',type:'전체',stage:'전체'};resourcesPage()};draw()}
function resourceDetail(slug){const r=resources.find(x=>x.slug===slug)||resources[0];const saved=(store.get().savedResources||[]).includes(r.slug);return pageHero(r.stage,r.title,r.desc)+`<section class="section"><div class="container content-grid"><nav class="side-nav"><a href="#target">대상·시점</a><a href="#how">작성 방법</a><a href="#example">가상 예시</a><a href="#download">다운로드</a><a href="/resources/">전체 자료실</a></nav><div><div id="target" class="detail-section"><h2>대상·사용 시점</h2><p>${r.stage} 단계에서 ${r.desc} 처음 작성하는 예비·초기 사업자가 항목을 빠뜨리지 않도록 돕는 실무용 자료입니다.</p></div><div id="how" class="detail-section"><h2>작성 방법</h2><ol class="detail-list"><li>확인된 사실과 가정을 구분해 입력합니다.</li><li>금액·일정·담당자를 가능한 구체적으로 기록합니다.</li><li>거래 또는 공식 제출 전에는 최신 조건과 원문을 다시 확인합니다.</li></ol>${r.slug==='contract-review'?'<p class="notice">계약 검토를 돕는 실무용 체크 자료이며 법률 자문이나 특정 거래에 대한 적합성 판단을 대신하지 않습니다.</p>':''}</div><div id="example" class="detail-section"><h2>가상 작성 예시</h2><p><strong>예시 사업:</strong> 지역 소상공인 대상 콘텐츠 제작 서비스</p><p><strong>작성 원칙:</strong> 실제 고객 인터뷰와 견적 조건을 근거로 수정하며, 예시 숫자와 문구를 그대로 사용하지 않습니다.</p></div><div id="download" class="download-box"><div><span class="badge">${r.format}</span><h3>${r.title} 빈 양식</h3><p>편집 가능한 파일 · 인쇄 설정 포함</p></div><a class="btn btn-blue" href="/downloads/${r.slug}.${r.format.toLowerCase()}" download>빈 양식 다운로드</a></div><div class="download-box" style="margin-top:12px;background:#fff7f1"><div><span class="badge">가상 예시</span><h3>${r.title} 작성 예시</h3><p>이해를 돕기 위한 가상의 내용입니다.</p></div><a class="btn" href="/downloads/${r.slug}-example.${r.format.toLowerCase()}" download>예시 다운로드</a></div><div class="actions" style="margin-top:22px"><button class="btn" id="save-resource">${saved?'저장 해제':'창업노트에 저장'}</button><a class="btn" href="/roadmap/${stages.find(x=>x.name===r.stage)?.slug||'before-start'}/">관련 단계 보기</a></div></div></div></section>`}
let supportFilter={q:'',type:'전체',region:'전체'};
function supportPage(){const seed=new URLSearchParams(location.search).get('q')||'';supportFilter.q=seed;main.innerHTML=pageHero('지원 경로 탐색','내 조건에 맞는 공식 확인 경로','현재 공고의 모집 여부·금액·마감일을 임의로 만들지 않습니다. 아래는 공식 기관에서 최신 공고를 확인하는 경로입니다.')+`<section class="section"><div class="container"><div class="notice"><strong>지원 경로 안내</strong><br>개별 모집 공고가 아닙니다. 신청 전 연령 산정 기준일, 거주지와 사업장 지역, 등록 시점, 업종 조건을 공식 원문에서 최종 확인하세요.</div><div class="filter-bar" style="margin-top:24px"><input class="input" id="support-q" value="${esc(seed)}" type="search" placeholder="기관·지원 내용 검색"><select id="support-type"><option>전체</option>${['보조금','융자','보증','공간','교육','판로·마케팅'].map(x=>`<option>${x}</option>`).join('')}</select><select id="support-region"><option>전체</option><option>전국</option><option>전국·지역</option><option>사업장 지역</option><option>지역 센터</option><option>온라인</option></select><button class="btn" id="support-reset">초기화</button></div><div id="support-list" class="list"></div></div></section>`;const draw=()=>{const f=supports.filter(s=>(supportFilter.type==='전체'||s.type===supportFilter.type)&&(supportFilter.region==='전체'||s.region===supportFilter.region)&&(`${s.name} ${s.org} ${s.desc} ${s.age} ${s.region}`.toLowerCase().includes(supportFilter.q.toLowerCase().replace('연령 제한 없음','연령 제한 없음').replace('40대 이상','정보 확인').replace('여성 창업','여성'))));document.querySelector('#support-list').innerHTML=f.length?f.map(s=>`<a class="list-item" href="/support/${s.slug}/"><div><div class="badges"><span class="badge official">공식 경로</span><span class="badge">${s.type}</span><span class="badge">${s.region}</span></div><h3>${s.name}</h3><p>${s.desc}</p><div class="meta">${s.org} · 연령: ${s.age} · 최종 확인: ${s.checked}</div></div><span>확인하기 ›</span></a>`).join(''):`<div class="empty"><h3>조건에 맞는 경로가 없습니다</h3><p>지역·연령 조건은 공고마다 다릅니다. 조건을 줄이거나 초기화해 보세요.</p></div>`};document.querySelector('#support-q').oninput=e=>{supportFilter.q=e.target.value;draw()};document.querySelector('#support-type').onchange=e=>{supportFilter.type=e.target.value;draw()};document.querySelector('#support-region').onchange=e=>{supportFilter.region=e.target.value;draw()};document.querySelector('#support-reset').onclick=()=>{history.replaceState({},'', '/support/');supportPage()};draw()}
function supportDetail(slug){const s=supports.find(x=>x.slug===slug)||supports[0];return pageHero('공식 지원 경로',s.name,s.desc)+`<section class="section"><div class="container policy"><div class="detail-section"><div class="badges"><span class="badge official">지원 경로 안내</span><span class="badge">${s.type}</span></div><h2>${s.org}</h2><dl><dt><strong>연령 조건</strong></dt><dd>${s.age} — 개별 공고의 연령 산정 기준일을 확인하세요.</dd><dt><strong>지역 기준</strong></dt><dd>${s.region} — 거주지와 사업장 소재지 조건을 구분하세요.</dd><dt><strong>사업 단계</strong></dt><dd>${s.stage}</dd><dt><strong>신청기간·준비서류</strong></dt><dd>개별 공고 원문에서 확인해야 합니다.</dd><dt><strong>실제 최종 확인일</strong></dt><dd>${s.checked}</dd></dl><p class="notice">새 법인 설립만으로 최초 창업이 되는 것은 아닙니다. 사업자등록 전에 신청해야 하는 조건도 있으니 등록 시점을 먼저 확인하세요.</p><div class="actions"><a class="btn btn-blue" href="${s.url}" target="_blank" rel="noopener">공식 원문 열기</a><button class="btn" id="save-support">관심 경로 저장</button></div></div></div></section>`}
function storiesPage(){return pageHero('실전 이야기','출발점이 달라도 실행 순서는 만들 수 있습니다','두 인물은 이해를 돕기 위한 가상 사례입니다. 서비스 기획 배경은 제공된 사실만 소개합니다.')+`<section class="section"><div class="container story-grid">${stories.map(x=>`<a class="story-card" href="/stories/${x.slug}/"><div class="story-visual">${x.icon}</div><div class="body"><span class="badge">${x.tag}</span><h2>${x.title}</h2><p>${x.lead}</p></div></a>`).join('')}</div></section>`}
function storyDetail(slug){const s=stories.find(x=>x.slug===slug)||stories[0];return pageHero('실전 이야기',s.title,s.lead)+`<section class="section"><div class="container policy"><p class="notice ${slug==='founder'?'':'notice-blue'}">${slug==='founder'?'제공된 기획 배경만 사용하며 확인되지 않은 성과나 사건은 소개하지 않습니다.':'이 이야기는 현실적인 과정을 설명하기 위해 만든 가상 사례입니다.'}</p>${s.steps.map(([h,p],i)=>`<div class="detail-section"><span class="result-stage">${i+1}</span><h2>${h}</h2><p>${p}</p></div>`).join('')}<div class="actions"><a class="btn btn-primary" href="/start/">내 단계 진단하기</a><a class="btn" href="/resources/">사용한 자료 보기</a></div></div></section>`}
function helpPage(){return pageHero('교육·도움받기','배우기부터 제작·운영까지','확인되지 않은 가격·일정·성공률은 표시하지 않습니다. 원하는 도움과 현재 상황을 정리해 문의 내용을 만들 수 있습니다.')+`<section class="section"><div class="container card-grid">${services.map((x,i)=>`<div class="card"><div style="font-size:42px">${x[4]}</div><span class="badge">${x[0]}</span><h2>${x[1]}</h2><h3>이런 분께</h3><p>${x[2]}</p><h3>진행 방식</h3><p>${x[3]}</p><a class="btn" href="/contact/?service=${i}">문의 내용 작성</a></div>`).join('')}</div></section>`}
function myPage(){const s=store.get(),stage=stages.find(x=>x.slug===s.stage);const savedR=(s.savedResources||[]).map(x=>resources.find(r=>r.slug===x)).filter(Boolean);const savedS=(s.savedSupports||[]).map(x=>supports.find(r=>r.slug===x)).filter(Boolean);return pageHero('내 창업노트','이 브라우저에 저장됩니다','로그인 없이 현재 브라우저의 로컬 저장소에만 보관됩니다. 다른 기기나 계정과 동기화되지 않습니다.')+`<section class="section"><div class="container note-dashboard"><div class="note-section"><h2>진단 결과</h2>${stage?`<span class="result-stage">${stage.name}</span><h3>${stage.summary}</h3><a class="btn" href="/roadmap/${stage.slug}/">단계 상세 보기</a>`:'<div class="empty"><p>아직 진단 결과가 없습니다.</p><a class="btn btn-blue" href="/start/">진단 시작</a></div>'}</div><div class="note-section"><h2>완료한 할 일</h2>${(s.completed||[]).length?(s.completed||[]).map(x=>`<div class="check-row">✓ ${esc(x)}</div>`).join(''):'<p class="muted">완료 표시한 할 일이 없습니다.</p>'}</div><div class="note-section"><h2>저장한 자료</h2>${savedR.length?savedR.map(x=>`<a class="check-row" href="/resources/${x.slug}/">${x.title}</a>`).join(''):'<p class="muted">저장한 자료가 없습니다.</p>'}</div><div class="note-section"><h2>관심 지원 경로</h2>${savedS.length?savedS.map(x=>`<a class="check-row" href="/support/${x.slug}/">${x.name}</a>`).join(''):'<p class="muted">저장한 지원 경로가 없습니다.</p>'}</div><div class="note-section wide"><h2>저장 데이터 관리</h2><p>초기화하면 이 브라우저에 저장된 진단 결과, 완료 할 일, 저장 자료, 관심 경로가 삭제됩니다.</p><button class="btn" id="clear-note">내 창업노트 초기화</button></div></div></section>`}
function corporation(){return pageHero('사업 형태 가이드','법인 설립·전환, 모두에게 정답은 아닙니다','책임 범위, 거래 구조, 비용, 세무와 투자 계획을 함께 보고 선택하세요. 실제 설립 전에는 최신 공식 절차와 전문가 의견을 확인하세요.')+`<section class="section"><div class="container policy"><div class="stat-grid"><div class="stat"><strong>1</strong>법인이 필요한 사업 이유</div><div class="stat"><strong>2</strong>유지 비용과 행정 부담</div><div class="stat"><strong>3</strong>거래·투자·책임 구조</div></div>${[['먼저 판단할 질문','개인사업으로 시작해 검증할 수 있는가? 공동창업자·투자·책임 분리가 지금 필요한가? 예상 거래처가 법인을 요구하는가?'],['설립 전에 확인할 것','상호·목적·자본금·주주·임원·본점, 업종별 인허가와 사업장 조건, 세무·4대보험·회계 운영 비용을 확인합니다.'],['전환 시 기록할 것','자산·계약·고객·직원·채무가 어떻게 이전되는지 목록으로 만들고, 기존 개인사업의 정리 절차를 별도로 확인합니다.'],['공식 확인','온라인 법인설립시스템, 인터넷등기소, 홈택스와 관할 기관의 최신 안내를 확인합니다.']].map(x=>`<div class="detail-section"><h2>${x[0]}</h2><p>${x[1]}</p></div>`).join('')}<p class="notice">이 안내는 일반 정보이며 법률·세무 자문을 대신하지 않습니다. 상황별 적용은 전문가와 공식 기관에 확인하세요.</p></div></section>`}
function about(){return pageHero('서비스 소개','흩어진 창업 정보를 실행 순서로','거상 창업내비는 처음 시작하는 사람이 지금 해야 할 일, 필요한 자료, 공식 지원 경로를 단계에 맞게 찾도록 돕습니다.')+`<section class="section"><div class="container split"><div class="detail-section"><h2>누구를 위한 서비스인가요?</h2><ul class="detail-list"><li>재직 중 창업을 준비하는 직장인</li><li>퇴사·퇴직·은퇴 후 시작하는 사람</li><li>경력 공백 이후 다시 시작하는 사람</li><li>사업을 운영하기 시작한 초보 사업자</li></ul></div><div class="detail-section"><h2>어떻게 돕나요?</h2><ol class="detail-list"><li>진단으로 현재 단계를 찾습니다.</li><li>오늘 할 일과 실무 자료를 연결합니다.</li><li>공식 지원 경로를 구분해 안내합니다.</li><li>더 필요한 교육·컨설팅·제작 도움을 선택합니다.</li></ol></div></div></section>`}
function contact(){const i=Number(new URLSearchParams(location.search).get('service')||0);return pageHero('문의 안내','상황을 정리해 문의 내용을 만드세요','현재 수신 서버와 확인된 연락 채널이 연결되지 않았습니다. 입력한 내용은 전송되지 않으며 복사하거나 텍스트 파일로 내려받을 수 있습니다.')+`<section class="section"><div class="container"><form class="contact-form" id="contact-form"><label>관심 서비스<select id="contact-service">${services.map((x,n)=>`<option ${n===i?'selected':''}>${x[0]} · ${x[1]}</option>`).join('')}</select></label><label>현재 상황<textarea id="contact-situation" rows="4" placeholder="현재 사업 단계와 가장 막히는 점을 적어주세요."></textarea></label><label>원하는 결과<textarea id="contact-goal" rows="4" placeholder="상담이나 제작을 통해 얻고 싶은 결과를 적어주세요."></textarea></label><label>참고 일정·조건<textarea id="contact-note" rows="3" placeholder="확정된 일정이 없다면 비워 두어도 됩니다."></textarea></label><div class="notice">이 화면은 문의 내용을 정리하는 도구입니다. 접수 또는 전송 완료로 처리되지 않습니다.</div><div class="contact-actions"><button class="btn btn-blue" type="button" id="copy-contact">문의 내용 복사</button><button class="btn" type="button" id="download-contact">텍스트 파일 다운로드</button></div></form></div></section>`}
function policy(type){const privacy=type==='privacy';return pageHero('운영정책 초안',privacy?'개인정보 처리방침':'이용약관',privacy?'첫 버전은 회원가입과 서버 저장 없이 브라우저 로컬 저장소만 사용합니다.':'서비스가 제공하는 정보와 자료의 범위, 이용 시 확인 사항을 안내합니다.')+`<section class="section"><div class="container policy">${(privacy?[['1. 처리하는 정보','창업 단계 진단 답변, 완료한 할 일, 저장한 자료와 관심 지원 경로는 사용자의 브라우저 로컬 저장소에만 보관됩니다. 서버로 전송하거나 계정과 연결하지 않습니다.'],['2. 저장과 삭제','사용자가 내 창업노트에서 초기화하거나 브라우저 저장 데이터를 삭제하면 제거됩니다.'],['3. 문의 내용','문의 작성 화면의 내용은 수신 서버로 전송되지 않습니다. 복사·다운로드는 사용자 기기에서 처리됩니다.'],['4. 외부 링크','공식 기관 사이트 이동 시 해당 기관의 개인정보 처리방침이 적용됩니다.'],['5. 운영 전 보완','실제 문의 채널, 분석 도구, 회원 기능이 추가되면 처리 항목·목적·보유기간·수탁자를 반영해 개정해야 합니다.']]:[['1. 서비스 범위','창업 단계 안내, 실무 양식, 공식 지원 경로와 교육·도움 정보를 제공합니다.'],['2. 정보의 한계','지원 자격, 법률·세무·노무 판단을 확정하지 않습니다. 사용자는 신청·계약·등록 전에 공식 원문과 전문가에게 최종 확인해야 합니다.'],['3. 자료 이용','직접 사용하는 실무 양식은 편집할 수 있으나 기관 발급 문서나 법정 서식을 대체하지 않습니다.'],['4. 지원사업','지원 경로 안내와 개별 공고를 구분합니다. 모집 여부·금액·마감일은 공식 원문이 우선합니다.'],['5. 책임과 변경','서비스는 확인 가능한 범위에서 정보를 제공하며, 운영 기능이나 실제 연락 채널 추가 시 정책을 보완합니다.']]).map(x=>`<h2>${x[0]}</h2><p>${x[1]}</p>`).join('')}<p class="muted">초안 기준일: 2026-09-29</p></div></section>`}
function bindPage(){const path=location.pathname.replace(/\/+$/,'')||'/';document.title=(path==='/'?'거상 창업내비':`${document.querySelector('h1')?.textContent||'거상 창업내비'} | 거상 창업내비`);document.querySelector('#save-resource')?.addEventListener('click',e=>{const slug=path.split('/')[2],s=store.get(),set=new Set(s.savedResources||[]);set.has(slug)?set.delete(slug):set.add(slug);store.patch({savedResources:[...set]});e.currentTarget.textContent=set.has(slug)?'저장 해제':'창업노트에 저장';toast(set.has(slug)?'창업노트에 저장했습니다.':'저장을 해제했습니다.')});document.querySelector('#save-support')?.addEventListener('click',()=>{const slug=path.split('/')[2],s=store.get(),set=new Set(s.savedSupports||[]);set.add(slug);store.patch({savedSupports:[...set]});toast('관심 지원 경로에 저장했습니다.')});document.querySelector('#clear-note')?.addEventListener('click',()=>{if(confirm('이 브라우저에 저장된 창업노트를 모두 초기화할까요?')){store.clear();render()}});const contactText=()=>`[거상 창업내비 문의 내용]\n관심 서비스: ${document.querySelector('#contact-service')?.value}\n\n현재 상황:\n${document.querySelector('#contact-situation')?.value}\n\n원하는 결과:\n${document.querySelector('#contact-goal')?.value}\n\n참고 일정·조건:\n${document.querySelector('#contact-note')?.value}\n`;document.querySelector('#copy-contact')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(contactText());toast('문의 내용을 복사했습니다. 전송되지는 않았습니다.')});document.querySelector('#download-contact')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([contactText()],{type:'text/plain;charset=utf-8'}));a.download='거상창업내비-문의내용.txt';a.click();URL.revokeObjectURL(a.href);toast('문의 내용을 내려받았습니다.')})}
function render(){const p=location.pathname.replace(/\/+$/,'')||'/';let html='';if(p==='/')html=home();else if(p==='/start'){startPage();return}else if(p==='/roadmap')html=roadmap();else if(p.startsWith('/roadmap/'))html=roadmapDetail(p.split('/')[2]);else if(p==='/resources'){resourcesPage();return}else if(p.startsWith('/resources/'))html=resourceDetail(p.split('/')[2]);else if(p==='/support'){supportPage();return}else if(p.startsWith('/support/'))html=supportDetail(p.split('/')[2]);else if(p==='/stories')html=storiesPage();else if(p.startsWith('/stories/'))html=storyDetail(p.split('/')[2]);else if(p==='/guides/corporation')html=corporation();else if(p==='/help')html=helpPage();else if(p==='/my')html=myPage();else if(p==='/about')html=about();else if(p==='/contact')html=contact();else if(p==='/privacy'||p==='/terms')html=policy(p.slice(1));else html=pageHero('404','페이지를 찾을 수 없습니다','주소를 확인하거나 홈에서 다시 시작해 주세요.')+`<section class="section"><div class="container"><a class="btn btn-blue" href="/">홈으로</a></div></section>`;main.innerHTML=html;bindPage();window.scrollTo(0,0)}
document.querySelector('.mobile-menu').onclick=e=>{const n=document.querySelector('.main-nav'),open=n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)};
const dialog=document.querySelector('#search-dialog'),input=document.querySelector('#global-search'),results=document.querySelector('#search-results');const searchIndex=[...stages.map(x=>({title:x.name,desc:x.summary,url:`/roadmap/${x.slug}/`,type:'로드맵'})),...resources.map(x=>({title:x.title,desc:x.desc,url:`/resources/${x.slug}/`,type:'자료'})),...supports.map(x=>({title:x.name,desc:x.desc,url:`/support/${x.slug}/`,type:'지원 경로'})),...stories.map(x=>({title:x.title,desc:x.lead,url:`/stories/${x.slug}/`,type:'이야기'}))];function doSearch(){const q=input.value.trim().toLowerCase();const found=q?searchIndex.filter(x=>`${x.title} ${x.desc} ${x.type}`.toLowerCase().includes(q)).slice(0,12):searchIndex.slice(0,6);results.innerHTML=found.length?found.map(x=>`<a class="search-result" href="${x.url}"><span class="badge">${x.type}</span><strong>${x.title}</strong><div class="meta">${x.desc}</div></a>`).join(''):'<div class="empty">검색 결과가 없습니다. 단어를 줄여 보세요.</div>'}document.querySelector('.search-open').onclick=()=>{dialog.showModal();doSearch();setTimeout(()=>input.focus(),50)};input.oninput=doSearch;
function syncMeta(){const h=document.querySelector('main h1')?.textContent?.trim();if(location.pathname!=='/'&&h)document.title=`${h} | 거상 창업내비`;const d=document.querySelector('main .section-desc')?.textContent?.trim();if(d)document.querySelector('meta[name="description"]')?.setAttribute('content',d)}
updateNoteCount();render();setTimeout(syncMeta,0);
